[package]
name = "zenlang"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.20", features = ["headers"] }
shuttle-axum = "0.34.1"
shuttle-runtime = { version = "0.34.1", default-features = false }
dotenv = "0.15.0"
handlebars = "4.3.7"
lettre = { version = "0.10.4", features = ["tokio1", "tokio1-native-tls"] }
serde = "1.0.189"
tower-http = { version = "0.4.4", features = ["full"] }
http = "0.2.9"
zen = {git = "https://github.com/zenlang-rs/zen-lang.git", branch = "main", version = "^0.2.1"}
jsonwebtoken = "9.1.0"
once_cell = "1.18.0"
shuttle-persist = "0.34.1"
bcrypt = "0.10.1"
httpc-test = "0.1.7"
anyhow = "1.0.75"
serde_json = "1.0.108"
rand = "0.8.5"
# serde_json = "1.0.108"
# mongodb = "2.0.0"
# tokio = "1.28.2"
# hyper = "0.14.27"
# tower = "0.4.13"
